const mockData = [
  {
    visitorId: '40123456',
    visitorName: 'ANA MENDOZA',
    visitorAge: 16,
    relationship: 'HERMANA',
    hostName: 'MARIA MENDOZA',
    hostId: '12345678',
    visitType: 'VISITA FAMILIAR',
    visitorDept: 'LIMA',
    visitorProv: 'LIMA',
    visitorDist: 'SAN JUAN DE LURIGANCHO',
  },
  {
    visitorId: '40234567',
    visitorName: 'BRUNO MENDOZA',
    visitorAge: 19,
    relationship: 'PRIMO',
    hostName: 'JULIO MENDOZA',
    hostId: '22345678',
    visitType: 'VISITA FAMILIAR',
    visitorDept: 'AREQUIPA',
    visitorProv: 'AREQUIPA',
    visitorDist: 'CERRO COLORADO',
  },
  {
    visitorId: '40345678',
    visitorName: 'CARLA MENDOZA',
    visitorAge: 18,
    relationship: 'TÍA',
    hostName: 'SOFÍA MENDOZA',
    hostId: '32345678',
    visitType: 'VISITA FAMILIAR',
    visitorDept: 'TRUJILLO',
    visitorProv: 'TRUJILLO',
    visitorDist: 'TRUJILLO',
  },
  {
    visitorId: '40456789',
    visitorName: 'DANIEL MENDOZA',
    visitorAge: 17,
    relationship: 'HERMANO',
    hostName: 'ELENA MENDOZA',
    hostId: '42345678',
    visitType: 'VISITA FAMILIAR',
    visitorDept: 'PIURA',
    visitorProv: 'PIURA',
    visitorDist: 'CATACAOS',
  },
  {
    visitorId: '40567890',
    visitorName: 'ESTEFANÍA MENDOZA',
    visitorAge: 20,
    relationship: 'PRIMA',
    hostName: 'FRANCISCO MENDOZA',
    hostId: '52345678',
    visitType: 'VISITA FAMILIAR',
    visitorDept: 'CUSCO',
    visitorProv: 'CUSCO',
    visitorDist: 'SAN JERÓNIMO',
  },
  {
    visitorId: '40678901',
    visitorName: 'FELIPE MENDOZA',
    visitorAge: 15,
    relationship: 'SOBRINO',
    hostName: 'PATRICIA MENDOZA',
    hostId: '62345678',
    visitType: 'VISITA FAMILIAR',
    visitorDept: 'JUNÍN',
    visitorProv: 'HUANCAYO',
    visitorDist: 'CHUPACA',
  },
  {
    visitorId: '40789012',
    visitorName: 'GABRIELA MENDOZA',
    visitorAge: 21,
    relationship: 'HIJA',
    hostName: 'ROBERTO MENDOZA',
    hostId: '72345678',
    visitType: 'VISITA FAMILIAR',
    visitorDept: 'LAMBAYEQUE',
    visitorProv: 'CHICLAYO',
    visitorDist: 'CHICLAYO',
  },
  {
    visitorId: '40890123',
    visitorName: 'HUGO MENDOZA',
    visitorAge: 22,
    relationship: 'CUÑADO',
    hostName: 'ALICIA MENDOZA',
    hostId: '82345678',
    visitType: 'VISITA FAMILIAR',
    visitorDept: 'ANCASH',
    visitorProv: 'HUARAZ',
    visitorDist: 'HUARAZ',
  },
  {
    visitorId: '40901234',
    visitorName: 'ISABEL MENDOZA',
    visitorAge: 16,
    relationship: 'AMIGA',
    hostName: 'MARIO MENDOZA',
    hostId: '92345678',
    visitType: 'VISITA FAMILIAR',
    visitorDept: 'ICA',
    visitorProv: 'ICA',
    visitorDist: 'ICA',
  },
  {
    visitorId: '41012345',
    visitorName: 'JAVIER MENDOZA',
    visitorAge: 18,
    relationship: 'SOBRINO',
    hostName: 'LUCÍA MENDOZA',
    hostId: '102345678',
    visitType: 'VISITA FAMILIAR',
    visitorDept: 'LIMA',
    visitorProv: 'LIMA',
    visitorDist: 'MIRAFLORES',
  },
  {
    visitorId: '41123456',
    visitorName: 'KARLA MENDOZA',
    visitorAge: 19,
    relationship: 'HERMANA',
    hostName: 'MIGUEL MENDOZA',
    hostId: '112345678',
    visitType: 'VISITA FAMILIAR',
    visitorDept: 'CALLAO',
    visitorProv: 'CALLAO',
    visitorDist: 'CALLAO',
  },
  {
    visitorId: '41234567',
    visitorName: 'LUCAS MENDOZA',
    visitorAge: 17,
    relationship: 'PRIMO',
    hostName: 'NORA MENDOZA',
    hostId: '122345678',
    visitType: 'VISITA FAMILIAR',
    visitorDept: 'AREQUIPA',
    visitorProv: 'AREQUIPA',
    visitorDist: 'SOCABAYA',
  },
  {
    visitorId: '41345678',
    visitorName: 'MARTA MENDOZA',
    visitorAge: 20,
    relationship: 'HERMANA',
    hostName: 'OSCAR MENDOZA',
    hostId: '132345678',
    visitType: 'VISITA FAMILIAR',
    visitorDept: 'LIMA',
    visitorProv: 'LIMA',
    visitorDist: 'ATE',
  },
  {
    visitorId: '41456789',
    visitorName: 'NATALIA MENDOZA',
    visitorAge: 15,
    relationship: 'PRIMA',
    hostName: 'PEDRO MENDOZA',
    hostId: '142345678',
    visitType: 'VISITA FAMILIAR',
    visitorDept: 'TACNA',
    visitorProv: 'TACNA',
    visitorDist: 'TACNA',
  },
  {
    visitorId: '41567890',
    visitorName: 'ÓSCAR MENDOZA',
    visitorAge: 21,
    relationship: 'SOBRINO',
    hostName: 'QUENI MENDOZA',
    hostId: '152345678',
    visitType: 'VISITA FAMILIAR',
    visitorDept: 'MOQUEGUA',
    visitorProv: 'MARISCAL NIETO',
    visitorDist: 'MOQUEGUA',
  },
  {
    visitorId: '41678901',
    visitorName: 'PAMELA MENDOZA',
    visitorAge: 18,
    relationship: 'HIJA',
    hostName: 'RAÚL MENDOZA',
    hostId: '162345678',
    visitType: 'VISITA FAMILIAR',
    visitorDept: 'LIMA',
    visitorProv: 'LIMA',
    visitorDist: 'SAN MARTÍN DE PORRES',
  },
  {
    visitorId: '41789012',
    visitorName: 'RENZO GARCIA',
    visitorAge: 17,
    relationship: 'PRIMO',
    hostName: 'SANDRA GARCIA',
    hostId: '172345678',
    visitType: 'VISITA FAMILIAR',
    visitorDept: 'LIMA',
    visitorProv: 'LIMA',
    visitorDist: 'BREÑA',
  },
  {
    visitorId: '41890123',
    visitorName: 'SARA GARCIA',
    visitorAge: 19,
    relationship: 'HERMANA',
    hostName: 'TOMÁS GARCIA',
    hostId: '182345678',
    visitType: 'VISITA FAMILIAR',
    visitorDept: 'LIMA',
    visitorProv: 'LIMA',
    visitorDist: 'PUEBLO LIBRE',
  },
  {
    visitorId: '41901234',
    visitorName: 'TOMÁS GARCIA',
    visitorAge: 16,
    relationship: 'SOBRINO',
    hostName: 'VANESSA GARCIA',
    hostId: '192345678',
    visitType: 'VISITA FAMILIAR',
    visitorDept: 'LIMA',
    visitorProv: 'LIMA',
    visitorDist: 'SURCO',
  },
  {
    visitorId: '42012345',
    visitorName: 'ULISES GARCIA',
    visitorAge: 20,
    relationship: 'CUÑADO',
    hostName: 'WILDER GARCIA',
    hostId: '202345678',
    visitType: 'VISITA FAMILIAR',
    visitorDept: 'LIMA',
    visitorProv: 'LIMA',
    visitorDist: 'LA MOLINA',
  },
];

export default mockData;
